Add encoding declaration and Python version check.
This makes the error message more helpful when accidentally using Python
2.X.

Before:

    $ python dothost
      File "dothost", line 3
    SyntaxError: Non-ASCII character '\xc2' in file dothost on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

After:

    $ python dothost
      File "dothost", line 29
        ...  # Python 3 is required
        ^
    SyntaxError: invalid syntax